export const SERVER_URL = "http://localhost:8080";
export const LOGIN_URL = "/";
export const LOGIN_API = "/login";
export const HOME_PAGE = "/homePage";
export const REGISTER_PAGE = "/register";
export const CHECK_OTP = "/check-otp-to-register";
export const GET_USERNAME_AND_GENDER = "/getUsername-and-gender";
export const GET_MATH = "/get-exercise";
export const GET_QUESTION_TYPE = "/get-question-type";
export const CHECK_ANSWER = "/check-answer";
export const CHECK_EXERCISE = "/check-exercise";
export const GET_USER_DATA = "/get-user-data";
export const GET_STATISTICS_DATA = "/get-statistic-data";
export const GET_EXERCISE_WITH_OPTION="/get-exercise-with-option";
export const GET_MULTIPLE_EXERCISES="/get-multiple-exercises";

export const TRANSITION = "src/assets/sounds/Transition.wav"
export const RIGHT_ANSWER = "src/assets/sounds/RightAnswer.wav"
export const WRONG_ANSWER = "src/assets/sounds/WrongAnswer.wav"
export const LEVEL_UP = "src/assets/sounds/LevelUp.wav"
export const GET_LEVEL = "/get-level";
export const PASSWORD_RECOVERY = "/passwordRecovery";
export const PASSWORD_RECOVERY_API = "/forgotten-password";
export const EMAIL_ALREADY_EXISTS = 1001;