import {
    SIMPLE_MATH_ISLAND,
    SIMPLE_MATH_ISLAND_BACKGROUND,
    MULTIPLICATION_ISLAND,
    MULTIPLICATION_ISLAND_BACKGROUND,
    DIVISION_ISLAND,
    DIVISION_ISLAND_BACKGROUND,
    FLOATING_POINT_ISLAND,
    FLOATING_POINT_ISLAND_BACKGROUND,
    LONG_ADDITION_SUBTRACTION_ISLAND,
    LONG_ADDITION_SUBTRACTION_ISLAND_BACKGROUND,
    LONG_MULTIPLICATION_DIVISION_ISLAND,
    LONG_MULTIPLICATION_DIVISION_ISLAND_BACKGROUND,
    HORROR_ISLAND,
    HORROR_ISLAND_BACKGROUND,
    EQUATIONS_ISLAND,
    EQUATIONS_ISLAND_BACKGROUND,
    SIMPLE_MATH_BACKGROUND,
    MULTIPLICATION_BACKGROUND,
    MULTIPLICATION_CHILDREN,
    SIMPLE_MATH_CHILDREN,
    SIMPLE_MATH_ISLAND_FLIPPED,
    MULTIPLICATION_ISLAND_FLIPPED,
    DIVISION_ISLAND_FLIPPED,
    DIVISION_BACKGROUND,
    DIVISION_CHILDREN,
    SIMPLE_MATH_CHILDREN_THINKING,
    MULTIPLICATION_CHILDREN_THINKING,
    SIMPLE_MATH_BOY,
    SIMPLE_MATH_GIRL,
    SIMPLE_MATH_BOY_HAPPY,
    SIMPLE_MATH_GIRL_HAPPY,
    MULTIPLICATION_BOY,
    MULTIPLICATION_BOY_HAPPY,
    MULTIPLICATION_GIRL,
    MULTIPLICATION_GIRL_HAPPY,
    FLOATING_POINT_ISLAND_FLIPPED,
    LONG_ADDITION_SUBTRACTION_ISLAND_FLIPPED,
    LONG_MULTIPLICATION_DIVISION_ISLAND_FLIPPED,
    HORROR_ISLAND_FLIPPED,
    EQUATIONS_ISLAND_FLIPPED,
    DIVISION_BALL,
    DIVISION_BALL_HAPPY,
    DIVISION_KIDS,
    DIVISION_KIDS_HAPPY,
    DIVISION_CHILDREN_THINKING,
} from "./IslandConstants.js";

// 💡 Main config as an array
const ISLAND_CONFIGS = [
    {
        id: 1,
        key: "simpleMathIsland",
        name: "אי החיבור והחיסור",
        className: "simpleMathIsland",
        island: SIMPLE_MATH_ISLAND,
        islandFlipped: SIMPLE_MATH_ISLAND_FLIPPED,
        background: SIMPLE_MATH_BACKGROUND,
        cardBackground: SIMPLE_MATH_ISLAND_BACKGROUND,
        children:SIMPLE_MATH_CHILDREN,
        child1:SIMPLE_MATH_BOY,
        child1Happy:SIMPLE_MATH_BOY_HAPPY,
        child2:SIMPLE_MATH_GIRL,
        child2Happy:SIMPLE_MATH_GIRL_HAPPY,
        childrenThinking:SIMPLE_MATH_CHILDREN_THINKING,
        url: "/island/simpleMathIsland",
        exerciseUrl:"/api/islands/Addition-and-subtraction",
        buttonColor: "green",
    },
    {
        id: 2,
        key: "multiplicationIsland",
        name: "אי הכפל",
        className: "multiplicationIsland",
        island: MULTIPLICATION_ISLAND,
        islandFlipped: MULTIPLICATION_ISLAND_FLIPPED,
        background: MULTIPLICATION_BACKGROUND,
        cardBackground: MULTIPLICATION_ISLAND_BACKGROUND,
        children: MULTIPLICATION_CHILDREN,
        child1:MULTIPLICATION_GIRL,
        child1Happy:MULTIPLICATION_GIRL_HAPPY,
        child2:MULTIPLICATION_BOY,
        child2Happy:MULTIPLICATION_BOY_HAPPY,
        childrenThinking:MULTIPLICATION_CHILDREN_THINKING,
        url: "/island/multiplicationIsland",
        exerciseUrl:"/api/islands/multiplication",
        buttonColor: "yellow",
    },
    {
        id: 3,
        key: "divisionIsland",
        name: "אי החילוק",
        className: "divisionIsland",
        island: DIVISION_ISLAND,
        islandFlipped: DIVISION_ISLAND_FLIPPED,
        background: DIVISION_BACKGROUND,
        cardBackground: DIVISION_ISLAND_BACKGROUND,
        children: DIVISION_CHILDREN,
        child1:DIVISION_BALL,
        child1Happy:DIVISION_BALL_HAPPY,
        child2:DIVISION_KIDS,
        child2Happy:DIVISION_KIDS_HAPPY,
        childrenThinking:DIVISION_CHILDREN_THINKING,
        url: "/island/divisionIsland",
        exerciseUrl:"/api/islands/division",
        buttonColor: "blue",
    },
    {
        id: 4,
        key: "floatingPointIsland",
        name: "האי העשרוני",
        className: "floatingPointIsland",
        island: FLOATING_POINT_ISLAND,
        islandFlipped: FLOATING_POINT_ISLAND_FLIPPED,
        cardBackground: FLOATING_POINT_ISLAND_BACKGROUND,
        url: "/island/floatingPointIsland",
        exerciseUrl:"/api/islands/floating-point",
        buttonColor: "orange",
    },
    {
        id: 5,
        key: "longAddSubIsland",
        name: "אי החיבור והחיסור הארוך",
        className: "longAddSubIsland",
        island: LONG_ADDITION_SUBTRACTION_ISLAND,
        islandFlipped: LONG_ADDITION_SUBTRACTION_ISLAND_FLIPPED,
        cardBackground: LONG_ADDITION_SUBTRACTION_ISLAND_BACKGROUND,
        url: "/island/longAddSubIsland",
        exerciseUrl:"/api/islands/long-addition-and-subtraction",
        buttonColor: "pink",
    },
    {
        id: 6,
        key: "longMultDivIsland",
        name: "אי הכפל והחילוק הארוך",
        className: "longMultDivIsland",
        island: LONG_MULTIPLICATION_DIVISION_ISLAND,
        islandFlipped: LONG_MULTIPLICATION_DIVISION_ISLAND_FLIPPED,
        cardBackground: LONG_MULTIPLICATION_DIVISION_ISLAND_BACKGROUND,
        url: "/island/longMultDivIsland",
        exerciseUrl:"/api/islands/long-multiplication-and-division",
        buttonColor: "white",
    },
    {
        id: 7,
        key: "horrorIsland",
        name: "האי הסיוטי",
        className: "horrorIsland",
        island: HORROR_ISLAND,
        islandFlipped: HORROR_ISLAND_FLIPPED,
        cardBackground: HORROR_ISLAND_BACKGROUND,
        url: "/island/horrorIsland",
        exerciseUrl:"/api/islands/mixed-challenge-island",
        buttonColor: "deepBlue",
    },
    {
        id: 8,
        key: "equationsIsland",
        name: "אי המשוואות",
        className: "equationsIsland",
        island: EQUATIONS_ISLAND,
        islandFlipped: EQUATIONS_ISLAND_FLIPPED,
        cardBackground: EQUATIONS_ISLAND_BACKGROUND,
        url: "/island/equationsIsland",
        exerciseUrl:"/api/islands/equations-island",
        buttonColor: "purple",
    },
];

// ✅ Map by key
const ISLAND_CONFIGS_MAP = ISLAND_CONFIGS.reduce((map, island) => {
    map[island.key] = island;
    return map;
}, {});

// ✅ Map by id (server id)
const ISLAND_CONFIGS_BY_ID = ISLAND_CONFIGS.reduce((map, island) => {
    map[island.id] = island;
    return map;
}, {});

export { ISLAND_CONFIGS, ISLAND_CONFIGS_MAP, ISLAND_CONFIGS_BY_ID };
